:figure-caption!:

image::https://app.wercker.com/status/f9aa9f4ae97d0f923ccfe0fa26c42c27/s[link="https://app.wercker.com/project/bykey/f9aa9f4ae97d0f923ccfe0fa26c42c27"]

= Vert.x examples

== Prerequisites
* JDK version 8 is installed on your system
* Make sure Vert.x is installed on your system and the `vertx` command is in your `PATH` (Vert.x can be downloaded from
https://bintray.com/artifact/download/vertx/downloads/vert.x-3.1.0-full.zip).

== Running
Run `./gradlew <project>:run` (on Linux/OSX) or `gradlew.bat <project>:run` (on Windows); where `<project>` is one of:

* `:client`
* `:message-sender`
* `:sockjs-eventbus-bridge`
* `:stocks-sender`

To run all modules at once (recommended to use full functionality), use `./gradlew --parallel run` (on Linux/OSX) or
`gradlew.bat --parallel run` (on Windows). Now you can browse to http://localhost:9000 to see the demo.

== Failover mode
If you want to run the application with failover functionality you need to have https://www.vagrantup.com/[Vagrant] and
https://www.virtualbox.org/[VirtualBox] installed and run `vagrant up` from the root folder before running the
application. Now, when killing one of the running applications, the Vert.x instance inside the VirtualBox instance takes
over.
