:figure-caption!:

image::https://app.wercker.com/status/f9aa9f4ae97d0f923ccfe0fa26c42c27/s[link="https://app.wercker.com/project/bykey/f9aa9f4ae97d0f923ccfe0fa26c42c27"]

= Vert.x examples

== Prerequisites
* JDK version 8 is installed on your system
* Make sure Vert.x is installed on your system and the `vertx` command is in your `PATH` (Vert.x can be downloaded from
https://bintray.com/artifact/download/vertx/downloads/vert.x-3.1.0-full.zip).

== Running
Make sure the project is built by running `./gradlew clean build`. After that you can run each
verticle by executing the following:

* `vertx run -cp ./client/build/libs/client.jar --ha com.mmjmanders.vertx.client.ClientVerticle`
* `vertx run -cp ./message-sender/build/libs/message-sender.jar --ha com.mmjmanders.vertx.sender.MessageSenderVerticle`
* `vertx run -cp ./sockjs-eventbus-bridge/build/libs/sockjs-eventbus-bridge.jar --ha com.mmjmanders.vertx.sockjs.SockJSEventBusBridgeVerticle`
* `vertx run -cp ./stocks-sender/build/libs/stocks-sender.jar --ha com.mmjmanders.vertx.stocks.StocksSenderVerticle`

It is recommended to run all verticles to see the full example by browsing to http://localhost:9000.

After running all of the above you can run `vagrant up` to start the VirtualBox machine (`Vagrant` and `VirtualBox` are
required to be installed on your system). When the machine is started you can kill the `message-sender` instance by
doing a `kill -9 <pid of message-sender>`. You can find the pid by executing `jps -m | grep Launcher` and find the
`message-sender` verticle. After that, the `vertx` instance inside the `VirtualBox` instance takes over and the client
keeps receiving messages.

== Failover mode
Make sure the project is built by running `./gradlew :bare:clean :bare:build`. Now run the server by executing
`vertx run -cp ./bare/build/libs/bare.jar --ha com.mmjmanders.vertx.bare.ServerVerticle`. Browse to http://localhost:8000
to see the result. Note the number before the `@`. Open a second terminal and run
`vertx bare -cp ./bare/build/libs/bare.jar`. When this is running open another terminal and execute
`kill -9 <number noted>`. After that the bare instance takes over and serves the verticle. You can verify this by again
browsing to http://localhost:8000. Notice the number before the `@` has changed.
